// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.5.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

List<NetDevStat> getNetDevStats() =>
    RustLib.instance.api.crateApiNetMonitorGetNetDevStats();

class NetDevStat {
  final BigInt ts;
  final String devId;
  final BigInt rxBytes;
  final BigInt txBytes;
  final bool statValid;

  const NetDevStat({
    required this.ts,
    required this.devId,
    required this.rxBytes,
    required this.txBytes,
    required this.statValid,
  });

  @override
  int get hashCode =>
      ts.hashCode ^
      devId.hashCode ^
      rxBytes.hashCode ^
      txBytes.hashCode ^
      statValid.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NetDevStat &&
          runtimeType == other.runtimeType &&
          ts == other.ts &&
          devId == other.devId &&
          rxBytes == other.rxBytes &&
          txBytes == other.txBytes &&
          statValid == other.statValid;
}
